name: CI/CD for UPM

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: flake8 upm/
      - name: Test Python
        run: pytest
      - name: Build & Benchmark Rust
        working-directory: ./upm/src
        run: |
          cargo build --release
          cargo bench --bench my_benchmark  # Using criterion.rs
      - name: Deploy (on main)
        if: github.ref == 'refs/heads/main'
        run: echo "Deploy script here"  # e.g., publish to PyPI